CONFIG_NAME: genesiscipherlabs
PRESET_BASE: genesiscipherlabs

# Genesis
GENESIS_FORK_VERSION: 0x20319988

# Altair
ALTAIR_FORK_VERSION: 0x30319988
ALTAIR_FORK_EPOCH: 0

# Bellatrix
BELLATRIX_FORK_VERSION: 0x40319988
BELLATRIX_FORK_EPOCH: 0
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_VERSION: 0x50319988
CAPELLA_FORK_EPOCH: 0

# Deneb
DENEB_FORK_VERSION: 0x60319988

# Electra
ELECTRA_FORK_VERSION: 0x70319988

# Fulu
FULU_FORK_VERSION: 0x80319988
FULU_FORK_EPOCH: 18446744073709551615


# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
